### ISSUE TITLE
How to Debug CSS Code

### ISSUE THREAD

**Issue by Baktygul-kk** [movers-kelechek/Introduction-to-CSS#5]

**Comment by kanyshaiosmonova** [comment]
У меня на это задание ушло аж 10 часов. Почему? 
 1)Изначально не могла открыть Debugger Problem 1 and Debugger Problem 2.  Очень много разных способов пробовала. Но не получалось. И тогда я написала Сайкал эже и попросила помочь мне. Она помогла мне несмотря на поздний час. 
2) Сам код легкий. Но на браузере ошибки не показывались. Я копалась в настройках  браузеров. Загружала разные расширения. Но консоль не показывал ошибку, даже если в коде есть ошибка. На это у меня ушло очень много времени.
