### ISSUE TITLE
The Anatomy of CSS Syntax

### ISSUE THREAD

**Issue by Baktygul-kk** [movers-kelechek/Introduction-to-CSS#6]

**Comment by saltanatdjan** [comment]
Была тема про синтаксис CSS. Тема было легкая кода было мало. В начале добавила немного слайдов презентации. И в конце записала видео. Видео записывала несколько раз, так как с первого раза не получилось. У меня ушло 5-6 часов так как нужно было придумать как лучше сделать, надо было выбрать командой шаблоны и обложку для видео. И запись уроков я только учусь делать и поэтому у меня это отнимает много времени.
